### ISSUE TITLE
User can view visualization of confirmed applicant enrollment.

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/pulse#13]
# 🥕  Motivation
I was users to be able to see, at a glance, the breakdown of enrollment based on enrollment details.

# 🏗  Implementation Details
- D3js

# 🔨  Tasks

- [ ] Draw wireframe
- [ ] Create async action creator to request list of confirmed applicants.
- [ ] Create route handler to route fetch request
- [ ] Query db and return enrollees 
- [ ] Create reducer to update state with confirmed applicant list.
- [ ] Create chart with D3
- [ ] Connect component to Redux state
