### ISSUE TITLE
Implement POST route to add applicant details to db. 

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/pulse#14]
# Motivation
We want to capture form data from Typeform, on our own server, in order to update our DB and applications. 

# Tasks
- [x] Set up webhook  with Typeform.
- [x] Use ngrok to test webook on localhost.
https://www.sitepoint.com/use-ngrok-test-local-site/
- [x] Implement POST route handler to handle the submitted application details.
- [x] Add applicant details to db.
