### ISSUE TITLE
Add mailer to allow outgoing email messages.

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/pulse#27]
# Motivation
We want to be alerted when an applicant submits and application.

# Implementation Details
~~Use the Nodemailer package to create and send emails.~~ 
Use the Sendgrid API to create and send emails. 
- I decided to go with Sendgrid because of its clean and simple API, with excellent documentation.

# Task List
- [x] Setup Sendgrid account
- [x] Implement function that creates the email
- [x] Implement function that sends the email
- [x] Create template email
