### ISSUE TITLE
Clean up file/directory structure. 

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/pulse#31]
# Motivation
I want to reorganize project logically, and eliminate all unused modules, and code that is no longer being used.

# Task List

- [x] Remove /build directory 
- The production build is now built to the dist directory, which is destroyed and created upon running `npm run build`.
- [x] Remove /src/server directory 
- This code has been refactored and moved to the /tools directory.
- [x] Rename /src/client/**components** to src/client/**features**
- I've reorganized the project structure by feature, instead of by category (components / actions / reducers etc).
- [x] Remove unused modules and code.

**Comment by farookisonfire** [comment]
# Task List
- [x] Address lint errors / warnings
- [x] Remove unused dependencies from package.json
