### ISSUE TITLE
Require user confirmation for accepting or denying an applicant.

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/pulse#41]
# Motivation
I want to give users the chance to confirm their Accept/Deny decision with a confirmation screen.

# Implementation Details
Use the Material-UI dialog(modal) component.

# Task List
- [x] Create ConfirmDecision component stateless functional component.
- [x] Implement handleModalOpen, handleModalClose, handleModalConfirm functions.
- [x] Dispatch updateApplicant async action creator on modal-confirm.

**Comment by farookisonfire** [comment]
![screen shot 2017-06-04 at 11 31 25 pm](https://cloud.githubusercontent.com/assets/19194235/26773020/f8b44b84-497d-11e7-8c88-ee756cb8c6b1.png)

**Comment by farookisonfire** [comment]
# Task List
- [x] Add Material-UI snackbar, to improve user experience.
